<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="DESKTOP-5OSSNT7" name="testcases.LoginTestCase" tests="7" failures="1" timestamp="2022-11-12T22:51:34 GMT-09:00" time="66.035" errors="0">
  <testcase name="excelverifyLoggedUsers" time="8.049" classname="testcases.LoginTestCase">
    <failure type="java.lang.AssertionError" message="title is not matching expected [Admin] but found [Admin2]">
      <![CDATA[java.lang.AssertionError: title is not matching expected [Admin] but found [Admin2]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.LoginTestCase.excelverifyLoggedUsers(LoginTestCase.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- excelverifyLoggedUsers -->
  <system-out/>
  <testcase name="excelverifyLoggedUsers" time="14.518" classname="testcases.LoginTestCase">
    <skipped/>
  </testcase> <!-- excelverifyLoggedUsers -->
  <system-out/>
  <testcase name="excelverifyLoggedUsers" time="9.384" classname="testcases.LoginTestCase">
    <skipped/>
  </testcase> <!-- excelverifyLoggedUsers -->
  <system-out/>
  <testcase name="excelverifyLoggedUsers" time="9.141" classname="testcases.LoginTestCase">
    <skipped/>
  </testcase> <!-- excelverifyLoggedUsers -->
  <system-out/>
  <testcase name="verifyLoggedUsers" time="8.193" classname="testcases.LoginTestCase"/>
  <system-out/>
  <testcase name="verifyCheckBox" time="8.369" classname="testcases.LoginTestCase"/>
  <system-out/>
  <testcase name="excelverifyLoggedUsers" time="8.381" classname="testcases.LoginTestCase">
    <skipped/>
  </testcase> <!-- excelverifyLoggedUsers -->
  <system-out/>
</testsuite> <!-- testcases.LoginTestCase -->
