<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-5OSSNT7" ignored="3" name="My Test Suite" tests="1" failures="1" timestamp="2022-11-01T12:48:08 IST" time="23.762" errors="0">
  <testcase name="imageHandling" time="10.425" classname="testcases.ManageExpensePage">
    <failure type="java.lang.AssertionError" message="no match expected [×/nAlert!/n Expense Record Updated Successfully] but found [×
Alert!
Expense Record Updated Successfully]">
      <![CDATA[java.lang.AssertionError: no match expected [×/nAlert!/n Expense Record Updated Successfully] but found [×
Alert!
Expense Record Updated Successfully]
at testcases.ManageExpensePage.imageHandling(ManageExpensePage.java:50)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- imageHandling -->
  <testcase name="callenderHandling" time="0.0" classname="testcases.ManageExpensePage">
    <ignored/>
  </testcase> <!-- callenderHandling -->
  <testcase name="manageResetButtonColorCheck" time="0.0" classname="testcases.ManageExpensePage">
    <ignored/>
  </testcase> <!-- manageResetButtonColorCheck -->
  <testcase name="manageNewButtonTextCheck" time="0.0" classname="testcases.ManageExpensePage">
    <ignored/>
  </testcase> <!-- manageNewButtonTextCheck -->
</testsuite> <!-- My Test Suite -->
